spring:
  application:
    name: account-master-service
  profiles:
    active:
    - dev
    include:
    - swagger
  
  datasource:
    url: jdbc:mysql://localhost:3306/bankdb?useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
       
    hibernate:
      ddl-auto: update

server:
  port: ${port:8181}
  error:
    include-message: on-param
    include-stacktrace: never
    include-binding-errors: always
    
management:
   endpoints:
    web:
      exposure:
        include:
        - refresh
